Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      ArtifactRelation:
        ecs_image_quickstart-coze-loop:
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
      SupplierTemplateConfigs:
        - Name: 模板1
          Url: 
            https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/template/08561084-4839-4280-bb31-d766e925004f.json?Expires=1754467787&OSSAccessKeyId=LTAI5tCYphFhocJemeMWmXst&Signature=loL2XtOOjjx16xQUdN30xPARwKA%3D
          PredefinedParameters: []
          AllowedRegions:
            - cn-qingdao
            - cn-beijing
            - cn-zhangjiakou
            - cn-huhehaote
            - cn-wulanchabu
            - cn-hangzhou
            - cn-shanghai
            - cn-shenzhen
            - cn-heyuan
            - cn-guangzhou
            - cn-wuhan-lr
            - cn-chengdu
            - cn-hongkong
            - ap-northeast-1
            - ap-northeast-2
            - ap-southeast-1
            - ap-southeast-3
            - ap-southeast-6
            - ap-southeast-5
            - ap-southeast-7
            - us-east-1
            - us-west-1
            - us-southeast-1
            - na-south-1
            - eu-west-1
            - me-east-1
            - me-central-1
            - eu-central-1
    TemplateConfigs:
      - Name: 模板1
        Url: ros_templates/template1.yaml
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - us-southeast-1
          - na-south-1
          - eu-west-1
          - me-east-1
          - me-central-1
          - eu-central-1
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      模板1:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Coze Loop 是一个面向开发者，专注于 AI Agent 开发与运维的平台级解决方案。 它可以解决 AI Agent 开发过程中面临的各种挑战，提供从开发、调试、评估、到监控的全生命周期管理能力。
    Image: resources/icons/service_logo.png
    Name: CozeLoop社区版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_quickstart-coze-loop
    Description: ecs_image_quickstart-coze-loop
    ArtifactProperty:
      ImageId: m-t4n5xqa0l6uz04m3t0mn
      RegionId: ap-southeast-1
    SupportRegionIds:
      - cn-qingdao
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-shenzhen
      - cn-chengdu
      - cn-heyuan
      - cn-guangzhou
      - cn-hongkong
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-5
      - ap-southeast-6
      - us-east-1
      - us-west-1
      - eu-west-1
      - eu-central-1
      - me-east-1
      - me-central-1
      - ap-southeast-7
      - ap-northeast-2
      - na-south-1
      - us-southeast-1
      - cn-wuhan-lr
